defmodule FluxWeb.Endpoint do
  use Desktop.Endpoint, otp_app: :flux

  # `desktop` 1.5.x picks its dynamic-port lookup strategy by matching the
  # Phoenix version against "~> 1.7.10", which excludes 1.8.x and falls back
  # to a Cowboy/:ranch-only code path. That path doesn't work with the
  # Bandit adapter used here, so re-override get_dynamic_port/1 with the
  # adapter-agnostic implementation (Phoenix.Endpoint.server_info/1).
  defoverridable get_dynamic_port: 1

  def get_dynamic_port(scheme) do
    {:ok, {_ip, port}} = server_info(scheme)
    port
  end

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_flux_key",
    signing_salt: "KsDox7p0",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :flux,
    gzip: not code_reloading?,
    only: FluxWeb.static_paths()

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :flux
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options

  # Only allow requests coming from this app's own native WebView window.
  # Skipped in test: ConnTest/LiveViewTest requests never carry the
  # per-run window auth token, so every request would otherwise 401.
  unless Mix.env() == :test do
    plug Desktop.Auth
  end

  plug FluxWeb.Router
end
